#include "core/rendering/screen.hpp"

#include <SDL3/SDL.h>

#include <algorithm>  // Para max, min, transform
#include <cctype>     // Para toupper
#include <cmath>      // Para round, floor
#include <cstring>    // Para memcpy
#include <fstream>    // Para basic_ostream, operator<<, endl, basic_...
#include <iostream>   // Para cerr
#include <iterator>   // Para istreambuf_iterator, operator==
#include <iomanip>    // Para setprecision
#include <sstream>    // Para ostringstream
#include <string>     // Para char_traits, string, operator+, operator==

#include "core/input/mouse.hpp"                       // Para updateCursorVisibility
#include "core/rendering/sdl3gpu/sdl3gpu_shader.hpp"  // Para SDL3GPUShader
#include "core/rendering/surface.hpp"                 // Para Surface, readPalFile
#include "core/rendering/text.hpp"                    // Para Text
#include "core/resources/resource_cache.hpp"          // Para Resource
#include "core/resources/resource_helper.hpp"         // Para ResourceHelper
#include "core/resources/resource_list.hpp"           // Para Asset, AssetType
#include "game/options.hpp"                           // Para Options, options, OptionsVideo, Border
#include "game/ui/console.hpp"                        // Para Console
#include "game/ui/notifier.hpp"                       // Para Notifier

// [SINGLETON]
Screen* Screen::screen = nullptr;

// [SINGLETON] Crearemos el objeto con esta función estática
void Screen::init() {
    Screen::screen = new Screen();
}

// [SINGLETON] Destruiremos el objeto con esta función estática
void Screen::destroy() {
    delete Screen::screen;
}

// [SINGLETON] Con este método obtenemos el objeto y podemos trabajar con él
auto Screen::get() -> Screen* {
    return Screen::screen;
}

// Constructor
Screen::Screen()
    : palettes_(Resource::List::get()->getListByType(Resource::List::Type::PALETTE)) {
    // Arranca SDL VIDEO, crea la ventana y el renderizador
    initSDLVideo();
    if (Options::video.fullscreen) { SDL_HideCursor(); }

    // Calcular tamaños y hacer .resize() de los buffers de píxeles
    adjustWindowSize();
    adjustRenderLogicalSize();
    updateZoomFactor();

    // Ajusta los tamaños
    game_surface_dstrect_ = {.x = Options::video.border.width, .y = Options::video.border.height, .w = Options::game.width, .h = Options::game.height};
    current_palette_ = findPalette(Options::video.palette);

    // Define el color del borde para el modo de pantalla completa
    border_color_ = static_cast<Uint8>(PaletteColor::BLACK);

    // Crea la textura donde se dibujan los graficos del juego
    game_texture_ = SDL_CreateTexture(renderer_, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, Options::game.width, Options::game.height);
    if (game_texture_ == nullptr) {
        // Registrar el error si está habilitado
        if (Options::console) {
            std::cerr << "Error: game_texture_ could not be created!\nSDL Error: " << SDL_GetError() << '\n';
        }
    }
    SDL_SetTextureScaleMode(game_texture_, SDL_SCALEMODE_NEAREST);

    // Crea la textura donde se dibuja el borde que rodea el area de juego
    border_texture_ = SDL_CreateTexture(renderer_, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, Options::game.width + (Options::video.border.width * 2), Options::game.height + (Options::video.border.height * 2));
    if (border_texture_ == nullptr) {
        // Registrar el error si está habilitado
        if (Options::console) {
            std::cerr << "Error: border_texture_ could not be created!\nSDL Error: " << SDL_GetError() << '\n';
        }
    }
    SDL_SetTextureScaleMode(border_texture_, SDL_SCALEMODE_NEAREST);

    // Cargar la paleta una sola vez
    auto initial_palette = readPalFile(palettes_.at(current_palette_));

    // Crea la surface donde se dibujan los graficos del juego
    game_surface_ = std::make_shared<Surface>(Options::game.width, Options::game.height);
    game_surface_->setPalette(initial_palette);
    game_surface_->clear(static_cast<Uint8>(PaletteColor::BLACK));

    // Crea la surface para el borde de colores
    border_surface_ = std::make_shared<Surface>(Options::game.width + (Options::video.border.width * 2), Options::game.height + (Options::video.border.height * 2));
    border_surface_->setPalette(initial_palette);
    border_surface_->clear(border_color_);

    // Cachear el color ARGB inicial del borde (borde sólido por defecto)
    border_surface_->toARGBBuffer(border_pixel_buffer_.data());
    border_argb_color_ = border_pixel_buffer_[0];

    // Establece la surface que actuará como renderer para recibir las llamadas a render()
    renderer_surface_ = std::make_shared<std::shared_ptr<Surface>>(game_surface_);

    // Crea el objeto de texto para la pantalla de carga
    createText();

    // Extrae el nombre de las paletas desde su ruta
    processPaletteList();

    // Renderizar una vez la textura vacía para que tenga contenido válido
    // antes de inicializar los shaders (evita pantalla negra)
    SDL_RenderTexture(renderer_, game_texture_, nullptr, nullptr);
    SDL_RenderTexture(renderer_, border_texture_, nullptr, nullptr);

    // Ahora sí inicializar los shaders
    initShaders();
}

// Destructor
Screen::~Screen() {
    SDL_DestroyTexture(game_texture_);
    SDL_DestroyTexture(border_texture_);
}

// Limpia el renderer
void Screen::clearRenderer(Color color) {
    SDL_SetRenderDrawColor(renderer_, color.r, color.g, color.b, 0xFF);
    SDL_RenderClear(renderer_);
}

// Prepara para empezar a dibujar en la textura de juego
void Screen::start() { setRendererSurface(nullptr); }

// Vuelca el contenido del renderizador en pantalla
void Screen::render() {
    fps_.increment();

    // Renderiza todos los overlays (escribe en game_surface_ CPU-side)
    renderOverlays();

    // En el path SDL3GPU, los píxeles se suben directamente desde la Surface.
    // En el path SDL_Renderer, primero copiamos la surface a la SDL_Texture.
    if (!(shader_backend_ && shader_backend_->isHardwareAccelerated())) {
        surfaceToTexture();
    }

    // Copia la textura al renderizador (o hace el present GPU)
    textureToRenderer();
}

// Establece el modo de video
void Screen::setVideoMode(bool mode) {
    // Actualiza las opciones
    Options::video.fullscreen = mode;

    // Configura el modo de pantalla y ajusta la ventana
    SDL_SetWindowFullscreen(window_, Options::video.fullscreen);
    SDL_SyncWindow(window_);
    adjustWindowSize();
    adjustRenderLogicalSize();
    updateZoomFactor();
}

// Camibia entre pantalla completa y ventana
void Screen::toggleVideoMode() {
    Options::video.fullscreen = !Options::video.fullscreen;
    setVideoMode(Options::video.fullscreen);
}

// Reduce el tamaño de la ventana
auto Screen::decWindowZoom() -> bool {
    if (static_cast<int>(Options::video.fullscreen) == 0) {
        const int PREVIOUS_ZOOM = Options::window.zoom;
        --Options::window.zoom;
        Options::window.zoom = std::max(Options::window.zoom, 1);

        if (Options::window.zoom != PREVIOUS_ZOOM) {
            setVideoMode(Options::video.fullscreen);
            return true;
        }
    }

    return false;
}

// Aumenta el tamaño de la ventana
auto Screen::incWindowZoom() -> bool {
    if (static_cast<int>(Options::video.fullscreen) == 0) {
        const int PREVIOUS_ZOOM = Options::window.zoom;
        ++Options::window.zoom;
        Options::window.zoom = std::min(Options::window.zoom, Options::window.max_zoom);

        if (Options::window.zoom != PREVIOUS_ZOOM) {
            setVideoMode(Options::video.fullscreen);
            return true;
        }
    }

    return false;
}

// Cambia el color del borde
void Screen::setBorderColor(Uint8 color) {
    border_color_ = color;
    border_surface_->clear(border_color_);

    // Actualizar caché ARGB del borde sólido (ocurre una vez por habitación, no cada frame)
    border_surface_->toARGBBuffer(border_pixel_buffer_.data());
    border_argb_color_ = border_pixel_buffer_[0];
    border_is_solid_ = true;
}

// Cambia entre borde visible y no visible
void Screen::toggleBorder() {
    Options::video.border.enabled = !Options::video.border.enabled;
    setVideoMode(Options::video.fullscreen);
    initShaders();
}

// Dibuja las notificaciones
void Screen::renderNotifications() const {
    if (notifications_enabled_) {
        Notifier::get()->render();
    }
    if (Console::get() != nullptr) {
        Console::get()->render();
    }
}

// Cambia el estado del PostFX
void Screen::togglePostFX() {
    Options::video.postfx = !Options::video.postfx;
    if (shader_backend_ && shader_backend_->isHardwareAccelerated()) {
        if (Options::video.postfx) {
            applyCurrentPostFXPreset();
        } else {
            // Pass-through: efectos a 0, el shader copia la textura sin modificar
            shader_backend_->setPostFXParams(Rendering::PostFXParams{});
        }
    } else {
        // Backend no inicializado aún — inicializarlo ahora
        initShaders();
    }
}

// Recarga el shader del preset actual sin toggle
void Screen::reloadPostFX() {
    if (Options::video.postfx && shader_backend_ && shader_backend_->isHardwareAccelerated()) {
        // El backend ya está activo: solo actualizar uniforms, sin recrear el pipeline
        applyCurrentPostFXPreset();
    } else if (Options::video.postfx) {
        initShaders();
    }
}

// Actualiza la lógica de la clase (versión nueva con delta_time para escenas migradas)
void Screen::update(float delta_time) {
    fps_.calculate(SDL_GetTicks());
    Notifier::get()->update(delta_time);
    if (Console::get() != nullptr) {
        Console::get()->update(delta_time);
    }
    Mouse::updateCursorVisibility();
}

// Calcula el tamaño de la ventana
void Screen::adjustWindowSize() {
    window_width_ = Options::game.width + (Options::video.border.enabled ? Options::video.border.width * 2 : 0);
    window_height_ = Options::game.height + (Options::video.border.enabled ? Options::video.border.height * 2 : 0);

    // Reservamos memoria una sola vez.
    // Si el buffer es más pequeño que la superficie, crash asegurado.
    border_pixel_buffer_.resize(static_cast<size_t>(window_width_ * window_height_));
    game_pixel_buffer_.resize(static_cast<size_t>(Options::game.width * Options::game.height));

    // border_pixel_buffer_ es el buffer que se sube a la GPU (tamaño total ventana).
    if (Options::video.border.enabled) {
        border_pixel_buffer_.resize(static_cast<size_t>(window_width_ * window_height_));
    }

    // Lógica de centrado y redimensionado de ventana SDL
    if (static_cast<int>(Options::video.fullscreen) == 0) {
        int old_w, old_h;
        SDL_GetWindowSize(window_, &old_w, &old_h);
        int old_x, old_y;
        SDL_GetWindowPosition(window_, &old_x, &old_y);

        const int NEW_X = old_x + ((old_w - (window_width_ * Options::window.zoom)) / 2);
        const int NEW_Y = old_y + ((old_h - (window_height_ * Options::window.zoom)) / 2);

        SDL_SetWindowSize(window_, window_width_ * Options::window.zoom, window_height_ * Options::window.zoom);
        SDL_SetWindowPosition(window_, std::max(NEW_X, WINDOWS_DECORATIONS), std::max(NEW_Y, 0));
    }
}

// Ajusta el tamaño lógico del renderizador
void Screen::adjustRenderLogicalSize() {
    SDL_SetRenderLogicalPresentation(renderer_, window_width_, window_height_, Options::video.integer_scale ? SDL_LOGICAL_PRESENTATION_INTEGER_SCALE : SDL_LOGICAL_PRESENTATION_LETTERBOX);
}

// Recalcula y almacena el factor de zoom. Llamar solo cuando SDL ya ha estabilizado el estado de la ventana.
// En ventana: Options::window.zoom (siempre entero).
// En fullscreen: mínimo de las escalas en ambos ejes; floor si integer scale está activo.
void Screen::updateZoomFactor() {
    if (!Options::video.fullscreen) {
        zoom_factor_ = static_cast<float>(Options::window.zoom);
        return;
    }
    if (window_width_ == 0 || window_height_ == 0) {
        zoom_factor_ = 1.0F;
        return;
    }
    int pw{0}, ph{0};
    SDL_GetRenderOutputSize(renderer_, &pw, &ph);
    const float SCALE = std::min(static_cast<float>(pw) / static_cast<float>(window_width_),
                                 static_cast<float>(ph) / static_cast<float>(window_height_));
    zoom_factor_ = Options::video.integer_scale ? std::floor(SCALE) : SCALE;
}

// Establece el renderizador para las surfaces
void Screen::setRendererSurface(const std::shared_ptr<Surface>& surface) {
    (surface) ? renderer_surface_ = std::make_shared<std::shared_ptr<Surface>>(surface) : renderer_surface_ = std::make_shared<std::shared_ptr<Surface>>(game_surface_);
}

// Cambia la paleta
void Screen::nextPalette() {
    ++current_palette_;
    if (current_palette_ == static_cast<int>(palettes_.size())) {
        current_palette_ = 0;
    }

    setPalete();
}

// Cambia la paleta
void Screen::previousPalette() {
    if (current_palette_ > 0) {
        --current_palette_;
    } else {
        current_palette_ = static_cast<Uint8>(palettes_.size() - 1);
    }

    setPalete();
}

// Establece la paleta
void Screen::setPalete() {  // NOLINT(readability-convert-member-functions-to-static)
    game_surface_->loadPalette(Resource::Cache::get()->getPalette(palettes_.at(current_palette_)));
    border_surface_->loadPalette(Resource::Cache::get()->getPalette(palettes_.at(current_palette_)));

    Options::video.palette = palettes_.at(current_palette_);

    // Eliminar ".gif"
    size_t pos = Options::video.palette.find(".pal");
    if (pos != std::string::npos) {
        Options::video.palette.erase(pos, 4);
    }

    // Convertir a mayúsculas
    std::ranges::transform(Options::video.palette, Options::video.palette.begin(), ::toupper);

    // Actualizar caché si el borde es sólido (la paleta cambia el valor ARGB del color)
    if (border_is_solid_) {
        border_surface_->toARGBBuffer(border_pixel_buffer_.data());
        border_argb_color_ = border_pixel_buffer_[0];
    }
}

// Extrae los nombres de las paletas
void Screen::processPaletteList() {
    for (auto& palette : palettes_) {
        palette = getFileName(palette);
    }
}

// Copia la surface a la textura
void Screen::surfaceToTexture() {  // NOLINT(readability-convert-member-functions-to-static)
    if (Options::video.border.enabled) {
        border_surface_->copyToTexture(renderer_, border_texture_);
        game_surface_->copyToTexture(renderer_, border_texture_, nullptr, &game_surface_dstrect_);
    } else {
        game_surface_->copyToTexture(renderer_, game_texture_);
    }
}

// Copia la textura al renderizador (o hace el present GPU)
void Screen::textureToRenderer() {
    if (shader_backend_ && shader_backend_->isHardwareAccelerated()) {
        const int GAME_W = Options::game.width;
        const int GAME_H = Options::game.height;

        if (Options::video.border.enabled) {
            const int BORDER_W = window_width_;
            const int BORDER_H = window_height_;
            const int OFF_X = static_cast<int>(game_surface_dstrect_.x);
            const int OFF_Y = static_cast<int>(game_surface_dstrect_.y);

            if (border_is_solid_) {
                // Path A: borde sólido (gameplay normal)
                // Rellena solo el marco con el color cacheado — sin lookups de paleta.
                // El área central (juego) se deja sin tocar; el overlay la sobreescribe igualmente.

                // Franjas superior e inferior (ancho completo)
                std::fill_n(border_pixel_buffer_.data(), OFF_Y * BORDER_W, border_argb_color_);
                std::fill_n(&border_pixel_buffer_[(OFF_Y + GAME_H) * BORDER_W],
                            (BORDER_H - OFF_Y - GAME_H) * BORDER_W, border_argb_color_);
                // Columnas laterales en las filas del área de juego
                for (int y = OFF_Y; y < OFF_Y + GAME_H; ++y) {
                    std::fill_n(&border_pixel_buffer_[y * BORDER_W], OFF_X, border_argb_color_);
                    std::fill_n(&border_pixel_buffer_[y * BORDER_W + OFF_X + GAME_W],
                                BORDER_W - OFF_X - GAME_W, border_argb_color_);
                }
            } else {
                // Path B: borde dinámico (escena de carga — bandas de colores animadas)
                // Conversión completa: la escena modifica border_surface_ cada frame
                border_surface_->toARGBBuffer(border_pixel_buffer_.data());
            }

            // Overlay del juego sobre el centro del buffer (ambos paths)
            game_surface_->toARGBBuffer(game_pixel_buffer_.data());
            for (int y = 0; y < GAME_H; ++y) {
                const Uint32* src = &game_pixel_buffer_[y * GAME_W];
                Uint32* dst = &border_pixel_buffer_[(OFF_Y + y) * BORDER_W + OFF_X];
                std::memcpy(dst, src, GAME_W * sizeof(Uint32));
            }

            shader_backend_->uploadPixels(border_pixel_buffer_.data(), BORDER_W, BORDER_H);
        } else {
            // Caso sin borde: subida directa simplificada
            game_surface_->toARGBBuffer(game_pixel_buffer_.data());
            shader_backend_->uploadPixels(game_pixel_buffer_.data(), GAME_W, GAME_H);
        }

        shader_backend_->render();
    } else {
        // Fallback SDL_Renderer (mantiene tu lógica de texturas SDL)
        SDL_Texture* tex = Options::video.border.enabled ? border_texture_ : game_texture_;
        SDL_SetRenderTarget(renderer_, nullptr);
        SDL_RenderClear(renderer_);
        SDL_RenderTexture(renderer_, tex, nullptr, nullptr);
        SDL_RenderPresent(renderer_);
    }
}

// Renderiza todos los overlays
void Screen::renderOverlays() {
    renderNotifications();
#ifdef _DEBUG
    renderInfo();
#endif
}

// Localiza la paleta dentro del vector de paletas
auto Screen::findPalette(const std::string& name) -> size_t {  // NOLINT(readability-convert-member-functions-to-static)
    std::string upper_name = toUpper(name + ".pal");

    for (size_t i = 0; i < palettes_.size(); ++i) {
        if (toUpper(getFileName(palettes_[i])) == upper_name) {
            return i;
        }
    }
    return static_cast<size_t>(0);
}

// Muestra información por pantalla
void Screen::renderInfo() const {
    if (!show_fps_ || text_ == nullptr) {
        return;
    }

    const int LINE_HEIGHT = text_->getCharacterSize() - 3;
    const int X = 0;
    int y = (Console::get() != nullptr) ? Console::get()->getVisibleHeight() : 0;

    // FPS
    const std::string FPS_TEXT = std::to_string(fps_.last_value) + " fps";
    text_->write(X, y, FPS_TEXT);
    y += LINE_HEIGHT;

    // Driver GPU
    text_->write(X, y, gpu_driver_.empty() ? "sdl" : gpu_driver_);
    y += LINE_HEIGHT;

    // Zoom calculado (alto físico / alto lógico), con coma decimal y sin ceros innecesarios
    const float ROUNDED = std::round(zoom_factor_ * 100.0F) / 100.0F;
    std::string zoom_str;
    if (ROUNDED == std::floor(ROUNDED)) {
        zoom_str = std::to_string(static_cast<int>(ROUNDED));
    } else {
        std::ostringstream oss;
        oss << std::fixed << std::setprecision(2) << ROUNDED;
        zoom_str = oss.str();
        if (zoom_str.back() == '0') { zoom_str.pop_back(); }
        std::replace(zoom_str.begin(), zoom_str.end(), '.', ',');
    }
    text_->write(X, y, zoom_str + "x");
    y += LINE_HEIGHT;

    // PostFX: muestra preset y supersampling en una sola línea, o nada si está desactivado
    if (Options::video.postfx) {
        std::string preset_name = "-";
        if (!Options::postfx_presets.empty()) {
            preset_name = Options::postfx_presets[static_cast<size_t>(Options::current_postfx_preset)].name;
        }
        const std::string POSTFX_LINE = preset_name + (Options::video.supersampling ? " (SS)" : "");
        text_->write(X, y, POSTFX_LINE);
    }
}

// Limpia la game_surface_
void Screen::clearSurface(Uint8 index) { game_surface_->clear(index); }

// Establece el tamaño del borde
void Screen::setBorderWidth(int width) { Options::video.border.width = width; }

// Establece el tamaño del borde
void Screen::setBorderHeight(int height) { Options::video.border.height = height; }

// Establece si se ha de ver el borde en el modo ventana
void Screen::setBorderEnabled(bool value) { Options::video.border.enabled = value; }

// Muestra la ventana
void Screen::show() { SDL_ShowWindow(window_); }

// Oculta la ventana
void Screen::hide() { SDL_HideWindow(window_); }

// Establece la visibilidad de las notificaciones
void Screen::setNotificationsEnabled(bool value) { notifications_enabled_ = value; }

// Activa / desactiva el contador de FPS
void Screen::toggleFPS() { show_fps_ = !show_fps_; }

// Alterna entre activar y desactivar el escalado entero
void Screen::toggleIntegerScale() {
    Options::video.integer_scale = !Options::video.integer_scale;
    SDL_SetRenderLogicalPresentation(renderer_, Options::game.width, Options::game.height, Options::video.integer_scale ? SDL_LOGICAL_PRESENTATION_INTEGER_SCALE : SDL_LOGICAL_PRESENTATION_LETTERBOX);
    if (shader_backend_) {
        shader_backend_->setScaleMode(Options::video.integer_scale);
    }
    updateZoomFactor();
}

// Alterna entre activar y desactivar el V-Sync
void Screen::toggleVSync() {
    Options::video.vertical_sync = !Options::video.vertical_sync;
    SDL_SetRenderVSync(renderer_, Options::video.vertical_sync ? 1 : SDL_RENDERER_VSYNC_DISABLED);
    if (shader_backend_) {
        shader_backend_->setVSync(Options::video.vertical_sync);
    }
}

// Getters
auto Screen::getRenderer() -> SDL_Renderer* { return renderer_; }
auto Screen::getRendererSurface() -> std::shared_ptr<Surface> { return (*renderer_surface_); }
auto Screen::getBorderSurface() -> std::shared_ptr<Surface> {
    border_is_solid_ = false;  // Modificación externa → modo borde dinámico
    return border_surface_;
}

auto loadData(const std::string& filepath) -> std::vector<uint8_t> {
    // Load using ResourceHelper (supports both filesystem and pack)
    return Resource::Helper::loadFile(filepath);
}

void Screen::setLinearUpscale(bool linear) {
    Options::video.linear_upscale = linear;
    if (shader_backend_ && shader_backend_->isHardwareAccelerated()) {
        shader_backend_->setLinearUpscale(linear);
    }
}

void Screen::setDownscaleAlgo(int algo) {
    Options::video.downscale_algo = algo;
    if (shader_backend_ && shader_backend_->isHardwareAccelerated()) {
        shader_backend_->setDownscaleAlgo(algo);
    }
}

// Activa/desactiva el supersampling global (Ctrl+F4)
void Screen::toggleSupersampling() {
    Options::video.supersampling = !Options::video.supersampling;
    if (Options::video.postfx && shader_backend_ && shader_backend_->isHardwareAccelerated()) {
        applyCurrentPostFXPreset();
    }
}

// Aplica los parámetros del preset actual al backend de shaders
void Screen::applyCurrentPostFXPreset() {  // NOLINT(readability-convert-member-functions-to-static)
    if (shader_backend_ && !Options::postfx_presets.empty()) {
        const auto& p = Options::postfx_presets[static_cast<size_t>(Options::current_postfx_preset)];
        // Supersampling es un toggle global (Options::video.supersampling), no por preset.
        // setOversample primero: puede recrear texturas antes de que setPostFXParams
        // decida si hornear scanlines en CPU o aplicarlas en GPU.
        shader_backend_->setOversample(Options::video.supersampling ? 3 : 1);
        Rendering::PostFXParams params{.vignette = p.vignette, .scanlines = p.scanlines, .chroma = p.chroma, .mask = p.mask, .gamma = p.gamma, .curvature = p.curvature, .bleeding = p.bleeding, .flicker = p.flicker};
        shader_backend_->setPostFXParams(params);
    }
}

// Inicializa los shaders
// El device GPU se crea siempre (independientemente de postfx) para evitar
// conflictos SDL_Renderer/SDL_GPU al hacer toggle F4 en Windows/Vulkan.
void Screen::initShaders() {
    SDL_Texture* tex = Options::video.border.enabled ? border_texture_ : game_texture_;

    if (!shader_backend_) {
        shader_backend_ = std::make_unique<Rendering::SDL3GPUShader>();
        shader_backend_->setPreferredDriver(Options::video.gpu_preferred_driver);
    }
    shader_backend_->init(window_, tex, "", "");
    gpu_driver_ = shader_backend_->getDriverName();

    // Propagar flags de vsync, integer scale, upscale y downscale al backend GPU
    shader_backend_->setVSync(Options::video.vertical_sync);
    shader_backend_->setScaleMode(Options::video.integer_scale);
    shader_backend_->setLinearUpscale(Options::video.linear_upscale);
    shader_backend_->setDownscaleAlgo(Options::video.downscale_algo);

    if (Options::video.postfx) {
        applyCurrentPostFXPreset();
    } else {
        // Pass-through: todos los efectos a 0, el shader solo copia la textura
        shader_backend_->setPostFXParams(Rendering::PostFXParams{});
    }
}

// Obtiene información sobre la pantalla
void Screen::getDisplayInfo() {  // NOLINT(readability-convert-member-functions-to-static)
    std::cout << "\n** VIDEO SYSTEM **\n";

    int num_displays = 0;
    SDL_DisplayID* displays = SDL_GetDisplays(&num_displays);
    if (displays != nullptr) {
        for (int i = 0; i < num_displays; ++i) {
            SDL_DisplayID instance_id = displays[i];
            const char* name = SDL_GetDisplayName(instance_id);

            std::cout << "Display " << instance_id << ": " << ((name != nullptr) ? name : "Unknown") << '\n';
        }

        const auto* dm = SDL_GetCurrentDisplayMode(displays[0]);

        // Guarda información del monitor en display_monitor_
        const char* first_display_name = SDL_GetDisplayName(displays[0]);
        display_monitor_.name = (first_display_name != nullptr) ? first_display_name : "Unknown";
        display_monitor_.width = static_cast<int>(dm->w);
        display_monitor_.height = static_cast<int>(dm->h);
        display_monitor_.refresh_rate = static_cast<int>(dm->refresh_rate);

        // Calcula el máximo factor de zoom que se puede aplicar a la pantalla
        Options::window.max_zoom = std::min(dm->w / Options::game.width, dm->h / Options::game.height);
        Options::window.zoom = std::min(Options::window.zoom, Options::window.max_zoom);

        // Muestra información sobre el tamaño de la pantalla y de la ventana de juego
        std::cout << "Current display mode: " << static_cast<int>(dm->w) << "x" << static_cast<int>(dm->h) << " @ " << static_cast<int>(dm->refresh_rate) << "Hz\n";

        std::cout << "Window resolution: " << static_cast<int>(Options::game.width) << "x" << static_cast<int>(Options::game.height) << " x" << Options::window.zoom << '\n';

        Options::video.info = std::to_string(static_cast<int>(dm->w)) + "x" +
            std::to_string(static_cast<int>(dm->h)) + " @ " +
            std::to_string(static_cast<int>(dm->refresh_rate)) + " Hz";

        // Calcula el máximo factor de zoom que se puede aplicar a la pantalla
        const int MAX_ZOOM = std::min(dm->w / Options::game.width, (dm->h - WINDOWS_DECORATIONS) / Options::game.height);

        // Normaliza los valores de zoom
        Options::window.zoom = std::min(Options::window.zoom, MAX_ZOOM);

        SDL_free(displays);
    }
}

// Arranca SDL VIDEO y crea la ventana
auto Screen::initSDLVideo() -> bool {
    // Inicializar SDL
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        std::cerr << "FATAL: Failed to initialize SDL_VIDEO! SDL Error: " << SDL_GetError() << '\n';
        return false;
    }

    // Obtener información de la pantalla
    getDisplayInfo();

    // Configurar hint para renderizado
#ifdef __APPLE__
    if (!SDL_SetHint(SDL_HINT_RENDER_DRIVER, "metal")) {
        std::cout << "WARNING: Failed to set Metal hint!\n";
    }
#endif

    // Crear ventana
    const auto WINDOW_WIDTH = Options::video.border.enabled ? Options::game.width + (Options::video.border.width * 2) : Options::game.width;
    const auto WINDOW_HEIGHT = Options::video.border.enabled ? Options::game.height + (Options::video.border.height * 2) : Options::game.height;
    SDL_WindowFlags window_flags = 0;
    if (Options::video.fullscreen) {
        window_flags |= SDL_WINDOW_FULLSCREEN;
    }
    window_ = SDL_CreateWindow(Options::window.caption.c_str(), WINDOW_WIDTH * Options::window.zoom, WINDOW_HEIGHT * Options::window.zoom, window_flags);

    if (window_ == nullptr) {
        std::cerr << "FATAL: Failed to create window! SDL Error: " << SDL_GetError() << '\n';
        SDL_Quit();
        return false;
    }

    // Crear renderer
    renderer_ = SDL_CreateRenderer(window_, nullptr);
    if (renderer_ == nullptr) {
        std::cerr << "FATAL: Failed to create renderer! SDL Error: " << SDL_GetError() << '\n';
        SDL_DestroyWindow(window_);
        window_ = nullptr;
        SDL_Quit();
        return false;
    }

    // Configurar renderer
    const int EXTRA_WIDTH = Options::video.border.enabled ? Options::video.border.width * 2 : 0;
    const int EXTRA_HEIGHT = Options::video.border.enabled ? Options::video.border.height * 2 : 0;
    SDL_SetRenderLogicalPresentation(
        renderer_,
        Options::game.width + EXTRA_WIDTH,
        Options::game.height + EXTRA_HEIGHT,
        Options::video.integer_scale ? SDL_LOGICAL_PRESENTATION_INTEGER_SCALE : SDL_LOGICAL_PRESENTATION_LETTERBOX);
    SDL_SetRenderDrawColor(renderer_, 0x00, 0x00, 0x00, 0xFF);
    SDL_SetRenderDrawBlendMode(renderer_, SDL_BLENDMODE_BLEND);
    SDL_SetRenderVSync(renderer_, Options::video.vertical_sync ? 1 : SDL_RENDERER_VSYNC_DISABLED);

    std::cout << "Video system initialized successfully\n";
    return true;
}

// Crea el objeto de texto
void Screen::createText() {  // NOLINT(readability-convert-member-functions-to-static)
    // Carga la surface de la fuente directamente del archivo
    auto surface = std::make_shared<Surface>(Resource::List::get()->get("aseprite.gif"));

    // Crea el objeto de texto (el constructor de Text carga el archivo text_file internamente)
    text_ = std::make_shared<Text>(surface, Resource::List::get()->get("aseprite.fnt"));
}